export const FETCH_ARTICLES_REQUEST = 'FETCH ARTICLES REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH ARTICLES SUCCESS';
export const FETCH_ARTICLES_FAILED = 'FETCH ARTICLES FAILED';
export const FETCH_TOPICS_REQUEST = 'FETCH TOPICS REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH TOPICS SUCCESS';
export const FETCH_TOPICS_FAILED = 'FETCH TOPICS FAILED';