export const FETCH_ARTICLE_REQUEST = 'FETCH ARTICLE REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH ARTICLE SUCCESS';
export const FETCH_ARTICLE_FAILED = 'FETCH ARTICLE FAILED';
export const FETCH_TOPICS_REQUEST = 'FETCH TOPICS REQUEST';